# Generated by Django 3.2 on 2022-08-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackBottle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sp_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackBottle.bottle'),
        ),
    ]
